name: herupa_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3
executables:
  herupa:

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  mustache_template: ^2.0.0
  pubspec_yaml: ^3.1.0
  recase: ^4.1.0
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
